#https://github.com/hashicorp/docker-consul
ARG CONSUL_VERSION
FROM consul:$CONSUL_VERSION
COPY ./ca.pem /usr/local/share/ca-certificates/ca.crt
RUN set -eux \
    update-ca-certificates \
    echo $(cat /usr/local/share/ca-certificates/ca.crt) >> /etc/ssl/certs/ca-certificates.crt
