---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consul
  namespace: vault-ns
  labels:
    app: consul
    layer: database
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
