apiVersion: v1
kind: Service
metadata:
  name: pod-test-simple-service
  namespace: default
spec:
  selector:
    app: pod-test-simple
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
