apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-configmap
  namespace: vault-ns
  labels:
    app: vault
    layer: application
data:
  extraconfig-from-values.hcl: |-
    disable_cache = true
    disable_mlock = true
    ui = true

    listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_disable = 1
    }

    listener "tcp" {
        address = "[::]:8300"
        tls_disable = 0
        tls_cert_file = "/cert/domain.pem"
        tls_key_file = "/cert/domain.key"
        tls_min_version = "tls12"
        tls_cipher_suites = "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        tls_prefer_server_cipher_suites = true
    }

    #storage "file" {
    #  path = "/vault/data"
    #}

    service_registration "kubernetes" {
      address        = "vault-consul-service:8500",
      namespace      = "vault-ns",
      pod_name       = "$VAULT_K8S_POD_NAME"
    }

    storage "consul" {
          address = "vault-consul-service:8500",
          path    = "vault/",
          disable_registration = true,
          ha_enable = true
    }

    max_lease_ttl = "10h"
    default_lease_ttl = "10h"
#    service_registration "kubernetes" {}

    #storage "consul"
    #  scheme: "https"
    #  tls_ca_file: /etc/tls/ca.pem
    #  tls_cert_file: /etc/tls/consul.pem
    #  tls_key_file: /etc/tls/consul-key.pem
