apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-data-volume
  namespace: default
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Users/olivier/Documents/GitHub/kube-vault-dockerhub/volume/data"
  capacity:
    storage: 1Gi
  claimRef:
    name: vault-data-volume-claim
    namespace: default
