apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-server-binding
  namespace: vault-ns
  labels:
    app: vault
    layer: application
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-role-register
subjects:
- kind: ServiceAccount
  name: vault-service-account
  namespace: vault-ns
