apiVersion: v1
kind: Service
metadata:
  name: vault-nginx-service
  namespace: vault-ns
  labels:
    app: nexus-nginx
    layer: reverseproxy
spec:
  selector:
    app: vault-nginx
  ports:
    - name: vault-nginx-https
      protocol: TCP
      port: 8300
      targetPort: 8300
