apiVersion: v1
kind: Secret
metadata:
  name: vault-secret-tls
  namespace: vault-ns
  labels:
    app: vault
    layer: application
type: Opaque
stringData:
  SSL_CERT_BUNDLE: |
    -----BEGIN CERTIFICATE-----
    MIIDYzCCAkugAwIBAgIUUdT6i7W6qKfZpXDgiTKXarlkEMYwDQYJKoZIhvcNAQEL
    BQAwKjEoMCYGA1UEAwwfcGtpX2t1YmUgSW50ZXJtZWRpYXRlIEF1dGhvcml0eTAe
    Fw0yMjA4MTIxMzUzNTdaFw0yMjA5MTExMzU0MjdaMBsxGTAXBgNVBAMTEHZhdWx0
    Lmt1YmUubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDht3p/
    j955cFSIC80NcBaGaSSaD5g15Kf/TLDVUmC/af4u+v0EvvSIX5hsnyfno492u/ML
    Q//VF06Aj+2hZbhcOFpxETvtsJ2cURgfAFl04MNg4T1RwKJAtauWrVaD9RvdZTzT
    jm6j5xus8CfKbKEP/KgIRqV/1oDUcuCeqfz+qU64Dpgag5OSMkg/Rex8toY/mfeW
    XCp0gfXWnwOv5Nv9oGIkGEIXRi6n2avLNyLul22HNXZrvU3VjLPcNOsQreiW0caC
    1CVBZMQNSf9XyZumaua9mZhIOieBFvCgI0acSmrYLOvRZNqQu97DyFQ8EDkLWOxY
    rP0JX3J0lvKZy0dzAgMBAAGjgY8wgYwwDgYDVR0PAQH/BAQDAgOoMB0GA1UdJQQW
    MBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNVHQ4EFgQUl3wMIe9I55aqfMNsF/sg
    YPs+ZocwHwYDVR0jBBgwFoAULXMXpu/LVENgU7HPvbGm/FIK48YwGwYDVR0RBBQw
    EoIQdmF1bHQua3ViZS5sb2NhbDANBgkqhkiG9w0BAQsFAAOCAQEAmLZF0Xhti9pA
    b70hmK55L4VLrUx0Td8VyGILODaKF0aG0zSqj7kSzhIsWVAvShM3BPjhHwdb/qqt
    PJNF3aLbMw/mhLr0eTxIh5SeTvGAO5pdW9pXBWvcIp1oYLfTdAGTDeVl+g1CLonc
    Zk4AS6lY91/VDBzluddTzvZTYigX6pgTYRIJxtvTyce8FrylPWCD8agIRNWCs/aO
    jv9bTwWKIc2B3iYmckLmpL4d5m89QkP8FKlsciXiIxlcd3bkPGIzpLZsbMHck2RJ
    VCQ4QxDD+OeuoowR+e+/bUbIIJPATHD5yPriLlTC34EoY9ZsyGIUF5NRXpiCVUbx
    I/6AB5VBmA==
    -----END CERTIFICATE-----
  SSL_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEA4bd6f4/eeXBUiAvNDXAWhmkkmg+YNeSn/0yw1VJgv2n+Lvr9
    BL70iF+YbJ8n56OPdrvzC0P/1RdOgI/toWW4XDhacRE77bCdnFEYHwBZdODDYOE9
    UcCiQLWrlq1Wg/Ub3WU8045uo+cbrPAnymyhD/yoCEalf9aA1HLgnqn8/qlOuA6Y
    GoOTkjJIP0XsfLaGP5n3llwqdIH11p8Dr+Tb/aBiJBhCF0Yup9mryzci7pdthzV2
    a71N1Yyz3DTrEK3oltHGgtQlQWTEDUn/V8mbpmrmvZmYSDongRbwoCNGnEpq2Czr
    0WTakLvew8hUPBA5C1jsWKz9CV9ydJbymctHcwIDAQABAoIBAAFH/VYEBwtBa/lp
    t7w/yqDwr9iABikoJxv333kWgp4Th/HUUuNYAiNUB5V2Qc+6yfGul26U8DrRawyn
    xH2KCkXbvAewRVrQCdT9UNm8MsXLENDX9nUkVsdvQI4WZctR9NqI3JOG13HuueV9
    Z3xqqW9hy8JgREg5e3m5PTUpWdpIMQJeQo6cl7PIvOYA+IQr+06lHvUMgI5PRGiU
    aM7yCRov4FvfAm7iuD7+zf1vSqUhkUHm+XRomVLaBKTUKhCJRATQmwb40iw4kmeW
    3UlntpiPXJh5dONrbvTiM95piuF9DoVj45IlXI9cZtXfpzcl9tqPVMQ8sKezLv40
    HxLNx4ECgYEA4ph8P8KLWoDyxYu8IELzYVzhi+84+Tw/AH2vLmnm3w6SnUwb4BGh
    f8O3wuoj3aXqmZULz+j9edbRycx3Gv0XmVOpleQM6ZA5zaGg5XVGUVYV1yO8bZF6
    r8zEIz84dTxngsWsWLFT+xMgU/vFN3/oba8hpdoUa6W5mdDLtCKRR2MCgYEA/wHL
    g8lqPlBByyMctWr3zb6kDJF87ThiHr45M08Lt/ajai3A/Z8AHpI0gBzAopWaqwVF
    nq1hC21KZrnaGerB+H9JVLImyh1i9k9CphYgMVn+7q55IdpPuYz88345wYZ3i4y2
    95MJgWbsnHv6Gs6cyD8vexe+fdof3TDKXXwlJLECgYBF1OJtr+HMWXL36FFoy9k/
    hyVHP8kaHjP4TcOAFUj+MvqCGWN50VUpD8MBAbFd7HT5MdK7Fz2On+J1Q1rtaVQt
    f3gC5o4IKNd3hLkWHec2x8XhUHUQe0YJCZzkk+YtUxk/VvX/O177QHC1ESE9MmEJ
    9G/1MdkbN66UNaGheQm2qwKBgE7881ki7nHW0kpl2eKn+5ITVyU9e4DPUjVLntQx
    y+Nz1jJxcbIdqh/OEc0NGu5BgOMwgtwfwEuV0tH3B4O3n9WlN8WwWSuJ5rl825wu
    hlJDGiA8kvDVepRzA3c4xhMX37euIo6VUQBwLSJblKDxFsdAKyjpteutwOj2z/gd
    GDRBAoGBAJO+KDu0etnX28VbPLotW7jS/+yRCIbnI3sYhUcKixZWuFRj//0BCeOV
    X+bxmRo4lOdQJ8mKp3W5UXq7WZ8aupgSlLBKiGbPydlb+XSds6tVe/xSmXgqhkzR
    MqaPHiMeuVRNFthX/p9iJ5ozV7Y5GoAWBQHxPmAga5lblR6bTrml
    -----END RSA PRIVATE KEY-----
  SSL_CA_BUNDLE: |
    -----BEGIN CERTIFICATE-----
    MIIDnzCCAoegAwIBAgIUArT2wLvu1Icb7fKkMT7VF73jMaUwDQYJKoZIhvcNAQEL
    BQAwEDEOMAwGA1UEAxMFbG9jYWwwHhcNMjIwODEyMTM0NzE1WhcNMjcwODExMTM0
    NzQ1WjAqMSgwJgYDVQQDDB9wa2lfa3ViZSBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApj5uNIEj74gLgZ/D3H+j
    JGFQuB4OeWTHOwGHPlj6N2Gfh4XJ1v4Tj5XEgODznaqNPP4iBRBIdTzkxMSgoHgd
    6QEA07wzFi8YJ2A70GZd3Cx/p5gcXOP3/Hf1Sn7xrUPQoB/ixqOWLqaBzy98pZTV
    6hd3pZyl7ddbRYWorubrR+NQHW2ofUAFHuq8TYET8m1R3kOnsvUYDh/Q4DU0qSgi
    DoJ2pmXUIvulRMI1lWNFeVGIEaZIN2MlIt9+hD6a4fTOz1YgK33ifTfTJai5gVhV
    UtxV86ZZftuOX56op6uk0coTJkHrgC/Ggj2tl7L3CZuO41E7YPFRZfuLVOye79pl
    SwIDAQABo4HWMIHTMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0G
    A1UdDgQWBBQtcxem78tUQ2BTsc+9sab8UgrjxjAfBgNVHSMEGDAWgBQrLAD5doHh
    bIwdZ9v6cZMcI0V6QzA8BggrBgEFBQcBAQQwMC4wLAYIKwYBBQUHMAKGIGh0dHA6
    Ly9sb2NhbGhvc3Q6NTIxMDAvdjEvcGtpL2NhMDIGA1UdHwQrMCkwJ6AloCOGIWh0
    dHA6Ly9sb2NhbGhvc3Q6NTIxMDAvdjEvcGtpL2NybDANBgkqhkiG9w0BAQsFAAOC
    AQEADW9gI5b4R+GFgRcr485JQRaMh4918Qighv1nR7sUkjv5fqwPG2oQf/RsNsSZ
    03BiJwLVymqqHOYZ/KgLkYrh1O0tu1Ekpjzo7cEtE+Si1ESrfJ3MJnHBic2rZ+Rw
    /sUXWFqak6lTQBcr+yPedNNBKQxKn3oOmUK+lwLricuEkbfDZUQRLbOTzOznerdq
    v2CzRJVaYmGCwmCFwIhdIFGlTJaSHIc5HZ8LZf92tKGY2laXsKqvUOhfYtZGdfvk
    7LyNem5uceGx1dyndm8dweNUB+9gTNY8tOqN6nahfyv1A2Ef+A4sreApD0fHjXNS
    MzaaHpqolfNAUEwhyr5gxzirJA==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDnzCCAoegAwIBAgIUArT2wLvu1Icb7fKkMT7VF73jMaUwDQYJKoZIhvcNAQEL
    BQAwEDEOMAwGA1UEAxMFbG9jYWwwHhcNMjIwODEyMTM0NzE1WhcNMjcwODExMTM0
    NzQ1WjAqMSgwJgYDVQQDDB9wa2lfa3ViZSBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApj5uNIEj74gLgZ/D3H+j
    JGFQuB4OeWTHOwGHPlj6N2Gfh4XJ1v4Tj5XEgODznaqNPP4iBRBIdTzkxMSgoHgd
    6QEA07wzFi8YJ2A70GZd3Cx/p5gcXOP3/Hf1Sn7xrUPQoB/ixqOWLqaBzy98pZTV
    6hd3pZyl7ddbRYWorubrR+NQHW2ofUAFHuq8TYET8m1R3kOnsvUYDh/Q4DU0qSgi
    DoJ2pmXUIvulRMI1lWNFeVGIEaZIN2MlIt9+hD6a4fTOz1YgK33ifTfTJai5gVhV
    UtxV86ZZftuOX56op6uk0coTJkHrgC/Ggj2tl7L3CZuO41E7YPFRZfuLVOye79pl
    SwIDAQABo4HWMIHTMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0G
    A1UdDgQWBBQtcxem78tUQ2BTsc+9sab8UgrjxjAfBgNVHSMEGDAWgBQrLAD5doHh
    bIwdZ9v6cZMcI0V6QzA8BggrBgEFBQcBAQQwMC4wLAYIKwYBBQUHMAKGIGh0dHA6
    Ly9sb2NhbGhvc3Q6NTIxMDAvdjEvcGtpL2NhMDIGA1UdHwQrMCkwJ6AloCOGIWh0
    dHA6Ly9sb2NhbGhvc3Q6NTIxMDAvdjEvcGtpL2NybDANBgkqhkiG9w0BAQsFAAOC
    AQEADW9gI5b4R+GFgRcr485JQRaMh4918Qighv1nR7sUkjv5fqwPG2oQf/RsNsSZ
    03BiJwLVymqqHOYZ/KgLkYrh1O0tu1Ekpjzo7cEtE+Si1ESrfJ3MJnHBic2rZ+Rw
    /sUXWFqak6lTQBcr+yPedNNBKQxKn3oOmUK+lwLricuEkbfDZUQRLbOTzOznerdq
    v2CzRJVaYmGCwmCFwIhdIFGlTJaSHIc5HZ8LZf92tKGY2laXsKqvUOhfYtZGdfvk
    7LyNem5uceGx1dyndm8dweNUB+9gTNY8tOqN6nahfyv1A2Ef+A4sreApD0fHjXNS
    MzaaHpqolfNAUEwhyr5gxzirJA==
    -----END CERTIFICATE-----
