apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vaults-home-1
spec:
  storageClassName: longhorn
  volumeMode: Filesystem
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: vault-ns
    name: pvc-vaults-home-vault-1
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: pvc-8fb85ae1-1f57-476a-a202-7b2a969361ee
