apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: vault-home-volume-claim
  namespace: vault-ns
  labels:
    app: vault
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
