apiVersion: v1
kind: Secret
metadata:
  name: vault-consul-nginx-secret-tls
  namespace: vault-ns
  labels:
    app: vault-consul-nginx
    layer: reverseproxy
type: Opaque
stringData:
  SSL_CERT_BUNDLE: |
    -----BEGIN CERTIFICATE-----
    MIIEijCCA3KgAwIBAgIUQWCHBayglgP95M/wD3vqy1yHsq4wDQYJKoZIhvcNAQEL
    BQAwdjELMAkGA1UEBhMCRlIxDTALBgNVBAgTBFJPT1QxDDAKBgNVBAcTA1RMUzEV
    MBMGA1UEChMMV29ybGRDb21wYW55MQswCQYDVQQLEwJDQTEmMCQGA1UEAxMdc2Vy
    dmVyLnZhdWx0LW5zLmNsdXN0ZXIubG9jYWwwHhcNMjIxMTA3MTk0NTAwWhcNMjMx
    MTA3MTk0NTAwWjB2MQswCQYDVQQGEwJGUjENMAsGA1UECBMEUk9PVDEMMAoGA1UE
    BxMDVExTMRUwEwYDVQQKEwxXb3JsZENvbXBhbnkxCzAJBgNVBAsTAkNBMSYwJAYD
    VQQDEx1zZXJ2ZXIudmF1bHQtbnMuY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcN
    AQEBBQADggEPADCCAQoCggEBAOKVAkWPrir5D3ozJgUKNrWjvrDLkHY+SRtLn3DA
    ab7T9kqlU4J4ZU11DaBB/3zVJh4+gNbVNug1U1dHvAM/B3h0/o6Kjre3jBMcxfQa
    +XgZU/HLeEDVOkzm14xx367ppqjj9dOjHBG7RU6dO68yEXHmk9jfuXK2jM/oMgm0
    AzA882Op7nfYIygZUrg+BtAhjkI+8W8Olb8cfR5xoC/DXJPnLGcqCGp08K0b6BBU
    6koFMX8gDQli6olZfWKLZmUMMae6IXS5NDI4IgHKi5G2QC/0z+WKDl42ND1d1LMy
    nNnb6Aj2QQaen0BlT4ilM6Orxbbrm+YEH+aQlP48IVhz5asCAwEAAaOCAQ4wggEK
    MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
    DAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUHbIsKa//oXu9mKDCE6YQ0CX7h7QwgasG
    A1UdEQSBozCBoIIRY29uc3VsLmt1YmUubG9jYWyCNXZhdWx0LWNvbnN1bC1uZ2lu
    eC1zZXJ2aWNlLnZhdWx0LW5zLnN2Yy5jbHVzdGVyLmxvY2Fsgi92YXVsdC1jb25z
    dWwtc2VydmljZS52YXVsdC1ucy5zdmMuY2x1c3Rlci5sb2NhbIIdY29uc3VsLnZh
    dWx0LW5zLmNsdXN0ZXIubG9jYWyHBH8AAAEwDQYJKoZIhvcNAQELBQADggEBAGBo
    IOxFLcrbbrzOdhNJXJoiAaxNZrFEOKRezQoN319dvh5D1WXUGx/4y+DtzYb3+FKA
    mEQj7yVdNILuX6ooP1plAPn/kv9GorWWgDks78vke1e43gAvoZbkVe7mMXAKFMUr
    pbRdbXVwC0uagZ+GeWE8pPwjtqWlvVN3T/xvtAdr+4E7nZViC6N2DiQe4kYbaAe2
    oXmH6uEOvNNsmu+u6I8HQrYJTx9HyIWjchv6RFckXze+TbZg2lAsgIOLDse+v4Ek
    Ycmq4xZCS9SMSrfpNpYhjGYXWF8fo58MxSMb1+FqgXXj0sntHorH8pSQqPkW+Sg+
    C4744rf95tQfFsfga6Q=
    -----END CERTIFICATE-----
  SSL_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpgIBAAKCAQEA4pUCRY+uKvkPejMmBQo2taO+sMuQdj5JG0ufcMBpvtP2SqVT
    gnhlTXUNoEH/fNUmHj6A1tU26DVTV0e8Az8HeHT+joqOt7eMExzF9Br5eBlT8ct4
    QNU6TObXjHHfrummqOP106McEbtFTp07rzIRceaT2N+5craMz+gyCbQDMDzzY6nu
    d9gjKBlSuD4G0CGOQj7xbw6Vvxx9HnGgL8Nck+csZyoIanTwrRvoEFTqSgUxfyAN
    CWLqiVl9YotmZQwxp7ohdLk0MjgiAcqLkbZAL/TP5YoOXjY0PV3UszKc2dvoCPZB
    Bp6fQGVPiKUzo6vFtuub5gQf5pCU/jwhWHPlqwIDAQABAoIBAQCZ8oRInwbHS9Go
    RXhflED3yPmXRbgxnsAtO4RpJ1KxxXJh5VKIIyUxK4bGjBD60BfGFNGVJejYfOLT
    OnoT+o8o2NTcJGgzixIxKiuVX36AizTt5EEgS8AA4Bcz5WsFfNsvhTNRSFGZ+pNs
    hog20N3pdbCeeeOWfVHPMQROc3B3JKspc9z662t8J/dhgfb76MLjbCzaQCzcMcP4
    MqiCYtwlhV0z58adcujUIvkVcLrCbCxa8ZzyvQ0Q4jwC9/cHZJcYcNfhAFXI9Ct2
    IxuL102ylScvQSanh5ltix0lv9REIWoI93ybAEFy0vSQTRJEfcQIgtVvZpOTev04
    AxZ/yHGBAoGBAPR561mxqm7gZslLY5A20oYiSnEjyBbgjBC0MlRcOrtMUgEAHSL2
    VZnsfiIEjo7GTbAoywgcLTs2+OFeExuoTMMkVH1HrMs0xdwMYaf9Hek79EZ1pnTm
    U88HQMdToZWxSNDriDJo+Z/F9Hjkz2HYMKq/L6N+mqMd+Zdg1cBAgxpHAoGBAO1D
    KVdVcjKgcfEKSBAjMuP+7+Z0aSJCYMX0AXoRGYSfmwqChqBu6pgdXQfcQMqGWDax
    3vRYCotGVMLOW896c0ZsieHjgOswt8pEzYNeNt7aac5PXqTqsbqLujJY3mxp2kx/
    8HZ0c84nz6J276cyI2SFcmR51RheK0USUE+Zdud9AoGBAJ8/s8DPbFehMRM6Wnac
    X3IkcB1W04Wja1mOJ6KwGUncIyanrlMR5xzG4jrCgSIbpotzZx23TPdfjaswHn5L
    mQUcazTYNYSAscnu/sXwqUU+WpZzGKTZTAp1jQrKPV1HCEmewy8jFkevKNp/IV94
    9eqjcyKq24wZgHXNDC+ZVk0NAoGBALPsoZY0GwTffWjAVkO+naIeu4i1MOElG0Qi
    tVf/Ta2wZ5/BuhxB4K94XQtP8OZkmNLpcl0zwtM5g5+zZBZkErUOLEXcA/DXIhlG
    sd70fIHleiVVNT21KRCBU7NIh2wJnd0zjIQX7ZYhxKi8ryLIt+RL+qLNbVcsWn3n
    1HV4uJ31AoGBAKOYWo4n0P08BF1XZ2JX8VKIBctyQZ9Lx12aiKBRlytKSOPijoXX
    H0tsr5DFBHgpPg6hR/h8Gqi6e9JNvx7QlODXUbmjHFtZZXIAhRVitD5RDAc76c4v
    yd7NTl51+Rn3st3JnzG/E6jpJMO7PNW2VGVX6oDZsrYgE/A+p642kzJV
    -----END RSA PRIVATE KEY-----
  SSL_CA_BUNDLE: |
    -----BEGIN CERTIFICATE-----
    MIIEijCCA3KgAwIBAgIUQWCHBayglgP95M/wD3vqy1yHsq4wDQYJKoZIhvcNAQEL
    BQAwdjELMAkGA1UEBhMCRlIxDTALBgNVBAgTBFJPT1QxDDAKBgNVBAcTA1RMUzEV
    MBMGA1UEChMMV29ybGRDb21wYW55MQswCQYDVQQLEwJDQTEmMCQGA1UEAxMdc2Vy
    dmVyLnZhdWx0LW5zLmNsdXN0ZXIubG9jYWwwHhcNMjIxMTA3MTk0NTAwWhcNMjMx
    MTA3MTk0NTAwWjB2MQswCQYDVQQGEwJGUjENMAsGA1UECBMEUk9PVDEMMAoGA1UE
    BxMDVExTMRUwEwYDVQQKEwxXb3JsZENvbXBhbnkxCzAJBgNVBAsTAkNBMSYwJAYD
    VQQDEx1zZXJ2ZXIudmF1bHQtbnMuY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcN
    AQEBBQADggEPADCCAQoCggEBAOKVAkWPrir5D3ozJgUKNrWjvrDLkHY+SRtLn3DA
    ab7T9kqlU4J4ZU11DaBB/3zVJh4+gNbVNug1U1dHvAM/B3h0/o6Kjre3jBMcxfQa
    +XgZU/HLeEDVOkzm14xx367ppqjj9dOjHBG7RU6dO68yEXHmk9jfuXK2jM/oMgm0
    AzA882Op7nfYIygZUrg+BtAhjkI+8W8Olb8cfR5xoC/DXJPnLGcqCGp08K0b6BBU
    6koFMX8gDQli6olZfWKLZmUMMae6IXS5NDI4IgHKi5G2QC/0z+WKDl42ND1d1LMy
    nNnb6Aj2QQaen0BlT4ilM6Orxbbrm+YEH+aQlP48IVhz5asCAwEAAaOCAQ4wggEK
    MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
    DAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUHbIsKa//oXu9mKDCE6YQ0CX7h7QwgasG
    A1UdEQSBozCBoIIRY29uc3VsLmt1YmUubG9jYWyCNXZhdWx0LWNvbnN1bC1uZ2lu
    eC1zZXJ2aWNlLnZhdWx0LW5zLnN2Yy5jbHVzdGVyLmxvY2Fsgi92YXVsdC1jb25z
    dWwtc2VydmljZS52YXVsdC1ucy5zdmMuY2x1c3Rlci5sb2NhbIIdY29uc3VsLnZh
    dWx0LW5zLmNsdXN0ZXIubG9jYWyHBH8AAAEwDQYJKoZIhvcNAQELBQADggEBAGBo
    IOxFLcrbbrzOdhNJXJoiAaxNZrFEOKRezQoN319dvh5D1WXUGx/4y+DtzYb3+FKA
    mEQj7yVdNILuX6ooP1plAPn/kv9GorWWgDks78vke1e43gAvoZbkVe7mMXAKFMUr
    pbRdbXVwC0uagZ+GeWE8pPwjtqWlvVN3T/xvtAdr+4E7nZViC6N2DiQe4kYbaAe2
    oXmH6uEOvNNsmu+u6I8HQrYJTx9HyIWjchv6RFckXze+TbZg2lAsgIOLDse+v4Ek
    Ycmq4xZCS9SMSrfpNpYhjGYXWF8fo58MxSMb1+FqgXXj0sntHorH8pSQqPkW+Sg+
    C4744rf95tQfFsfga6Q=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE REQUEST-----
    MIIDfjCCAmYCAQAwdjELMAkGA1UEBhMCRlIxDTALBgNVBAgTBFJPT1QxDDAKBgNV
    BAcTA1RMUzEVMBMGA1UEChMMV29ybGRDb21wYW55MQswCQYDVQQLEwJDQTEmMCQG
    A1UEAxMdc2VydmVyLnZhdWx0LW5zLmNsdXN0ZXIubG9jYWwwggEiMA0GCSqGSIb3
    DQEBAQUAA4IBDwAwggEKAoIBAQDIHPTlsLffAFlxCDS/8FtOW6i+UmYYcPsxwaJx
    kwnBt71yK0HS/yc7FzW7Q95qAV6lq37O4Q5+2qUms/3ysStmXqCjwNBRsXoQRgue
    Ca4O/rvXu5PgeQAxV378lQgIJ/hnuxvP9AeGyEg+Ij79sEBK45FGo10Gu44PwwJ4
    2SRCaxYwEGyOQ2P5lnbKP+zghpWVQ+xry/7x+VFhfGEfgAb/7YGlzwiEnU8QcWS6
    3F1zNVDqw3c9iUsFYJegLH4zW5hFQ/xaoeadRlhjdAnsyLDWKDTk+fgdwg7MOR2v
    ihW/VkvWPw54n1RP3EsLYW97OHmSeWlhvlAw4AL6ug8IELvxAgMBAAGggcIwgb8G
    CSqGSIb3DQEJDjGBsTCBrjCBqwYDVR0RBIGjMIGgghFjb25zdWwua3ViZS5sb2Nh
    bII1dmF1bHQtY29uc3VsLW5naW54LXNlcnZpY2UudmF1bHQtbnMuc3ZjLmNsdXN0
    ZXIubG9jYWyCL3ZhdWx0LWNvbnN1bC1zZXJ2aWNlLnZhdWx0LW5zLnN2Yy5jbHVz
    dGVyLmxvY2Fsgh1jb25zdWwudmF1bHQtbnMuY2x1c3Rlci5sb2NhbIcEfwAAATAN
    BgkqhkiG9w0BAQsFAAOCAQEAtdRZXhErZ5iMfmQ8gCIcd+7g7pr4Snz1U9NZCQHA
    zDhlEsYTK4e4R3E2cc7uzwmZ4pTE3UCnw557J3uPaH81p3t+fGBVFh2YatTHncim
    bVtSl5oYgonbriL6+9GYPNbb9tA1QdslHjKmYGVeKCN3cmi8X94UJ2L3Jr8t2242
    ZLUrWOBv6bA+5CLMejepFZ1rdvXmkhgtsaV02jiLOMM9sEmeASwNJRHeGQCq9kgC
    9zj0KbnihLLplUfxnPAqOI/I8+c9gvbXqbQZ+PWbAS7vZGygUAlnHxvuzDoYeyA8
    L6WZVcExyJ7/ttnkMAxH35EZKKFuZpPmdraE+uJNxIk3JA==
    -----END CERTIFICATE REQUEST-----
