apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-kube-tls
  namespace: vault-ns
spec:
  # Secret names are always required.
  secretName: vault-kube-tls

  # secretTemplate is optional. If set, these annotations and labels will be
  # copied to the Secret named example-com-tls. These labels and annotations will
  # be re-reconciled if the Certificate's secretTemplate changes. secretTemplate
  # is also enforced, so relevant label and annotation changes on the Secret by a
  # third party will be overwriten by cert-manager to match the secretTemplate.
  secretTemplate:
    annotations:
      my-secret-annotation-1: "vault"
      my-secret-annotation-2: "kube"
    labels:
      my-secret-label: "vault-kube-tls"

  duration: 24h
  renewBefore: 8h
  subject:
    organizations:
      - vault
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: vault.kube.local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
    #- digital signature
    #- key encipherment
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - vault.kube.local
  #uris:
  # - spiffe://cluster.local/ns/default/sa/vault
  #ipAddresses:
  # - 192.168.0.5
  # Issuer references are always required.
  issuerRef:
    name: vault-kube-clusterissuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
