apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: vault-ns
  labels:
    app: vault
spec:
  serviceName: vault-internal
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault-service-account
      securityContext:
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 100
        fsGroup: 1000
      containers:
        - name: vault
          image: hashicorp/vault:1.9.7 #1.12.0
          imagePullPolicy: Always
          command:
          - "/bin/sh"
          - "-ec"
          args:
          - |
            cp /vault/config/extraconfig-from-values.hcl /tmp/storageconfig.hcl;
            [ -n "${HOST_IP}" ] && sed -Ei "s|HOST_IP|${HOST_IP?}|g" /tmp/storageconfig.hcl;
            [ -n "${POD_IP}" ] && sed -Ei "s|POD_IP|${POD_IP?}|g" /tmp/storageconfig.hcl;
            [ -n "${HOSTNAME}" ] && sed -Ei "s|HOSTNAME|${HOSTNAME?}|g" /tmp/storageconfig.hcl;
            [ -n "${API_ADDR}" ] && sed -Ei "s|API_ADDR|${API_ADDR?}|g" /tmp/storageconfig.hcl;
            [ -n "${TRANSIT_ADDR}" ] && sed -Ei "s|TRANSIT_ADDR|${TRANSIT_ADDR?}|g" /tmp/storageconfig.hcl;
            [ -n "${RAFT_ADDR}" ] && sed -Ei "s|RAFT_ADDR|${RAFT_ADDR?}|g" /tmp/storageconfig.hcl;
            /usr/local/bin/docker-entrypoint.sh vault server -config=/tmp/storageconfig.hcl
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
              add: ['IPC_LOCK']
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VAULT_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: VAULT_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VAULT_ADDR
              value: "https://vault.kube.local"
            - name: VAULT_API_ADDR
              value: "https://vault.kube.local"
            - name: SKIP_CHOWN
              value: "true"
            - name: SKIP_SETCAP
              value: "true"
            - name: VAULT_CLUSTER_ADDR
              value: "https://$(HOSTNAME).vault-internal:8201"
            - name: HOME
              value: "/home/vault"
          ports:
            - name: http
              containerPort: 8200
            - name: https
              containerPort: 8300
            - name: https-internal
              containerPort: 8201
            - name: http-rep
              containerPort: 8202
          resources:
            limits:
              cpu: 500m
              memory: 3Gi
            requests:
              cpu: 10m
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: 8300
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8300
            failureThreshold: 6
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - name: vault-data-volume
              mountPath: /vault/data
            - name: vault-config-volume
              mountPath: /vault/config
            - name: vault-home-volume
              mountPath: /home/vault
            - name: pod-cert
              mountPath: "/cert"
      volumes:
        - name: vault-data-volume
          persistentVolumeClaim:
            claimName: vault-data-volume-claim
        - name: vault-home-volume
          persistentVolumeClaim:
            claimName: vault-home-volume-claim
        - name: vault-config-volume
          configMap:
            name: vault-configmap
            items:
            - key: extraconfig-from-values.hcl
              path: extraconfig-from-values.hcl
        - name: pod-cert
          csi:
            driver: csi.cert-manager.io
            readOnly: true
            volumeAttributes:
                csi.cert-manager.io/issuer-kind: ClusterIssuer
                csi.cert-manager.io/issuer-name: vault-cluster-clusterissuer
                csi.cert-manager.io/issuer-group: cert-manager.io
                csi.cert-manager.io/common-name: vault.cluster.local
                csi.cert-manager.io/dns-names: ${POD_NAME}.${POD_NAMESPACE}.pod.cluster.local
                csi.cert-manager.io/duration: 12h
                csi.cert-manager.io/renew-before: 4h
                csi.cert-manager.io/is-ca: "false"
                csi.cert-manager.io/key-usages: digital signature,key encipherment,server auth,client auth
                csi.cert-manager.io/certificate-file: domain.pem
                csi.cert-manager.io/privatekey-file: domain.key
                csi.cert-manager.io/ca-file: ca.pem
