apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-kube-clusterissuer
  namespace: vault-ns
spec:
  vault:
    path: pki_kube/sign/pki_kube-role
    server: http://vault-service
    #server: vault.kube.local
    #caBundle: <base64 encoded caBundle PEM file>
    auth:
      appRole:
        path: approle
        roleId: 8f0497a3-87c1-c4ed-1ef6-7c3872282c6c
        secretRef:
          name: cert-manager-secret-approle-kube
          key: SECRET_ID
