# kubectl -n vault-ns exec -it consul-0 -- /bin/sh
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
  namespace: vault-ns
  labels:
    app: consul
    role: server
    layer: database
spec:
  selector:
    matchLabels:
      app: consul
      role: server
  serviceName: consul
  podManagementPolicy: "Parallel"
  replicas: 4
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: consul
        role: server
    spec:
      serviceAccountName: consul
      securityContext:
        fsGroup: 1000
      containers:
      - name: consul
        image: l_consul:latest
        imagePullPolicy: Never

        env:

          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

          - name: GOSSIP_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: consul
                key: gossip-encryption-key

        args:

          - "agent"
          - "-advertise=$(POD_IP)"
          - "-bootstrap-expect=4"
          - "-config-file=/etc/consul/config/config.json"
          - "-encrypt=$(GOSSIP_ENCRYPTION_KEY)"

        livenessProbe:

          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep consul
          initialDelaySeconds: 5
          timeoutSeconds: 2

        readinessProbe:

          httpGet:
            path: /v1/status/peers
            port: 8500
          initialDelaySeconds: 30
          timeoutSeconds: 5

        ports:

        - containerPort: 8500
          name: ui-http
        - containerPort: 8501
          name: ui-https
        - containerPort: 8600
          name: dns-udp
          protocol: UDP
        - containerPort: 8600
          name: dns-tcp
          protocol: TCP

        volumeMounts:

        - name: consul-config
          mountPath: /etc/consul/config

        - name: consul-data
          mountPath: /consul/data

        - name: pod-cert
          mountPath: "/etc/tls/"

      volumes:

      - name: consul-config
        configMap:
          name: consul-config

      - name: pod-cert
        csi:
          driver: csi.cert-manager.io
          readOnly: true
          volumeAttributes:
            csi.cert-manager.io/issuer-kind: Issuer
            csi.cert-manager.io/issuer-name: vault-pki-sec-issuer
            csi.cert-manager.io/issuer-group: cert-manager.io
            csi.cert-manager.io/common-name: consul.cluster.local
            csi.cert-manager.io/dns-names: ${POD_NAME}.${POD_NAMESPACE}.pod.cluster.local
            csi.cert-manager.io/duration: 720h
            csi.cert-manager.io/renew-before: 4h
            csi.cert-manager.io/is-ca: "false"
            csi.cert-manager.io/key-usages: digital signature,key encipherment,server auth,client auth
            csi.cert-manager.io/certificate-file: consul.pem
            csi.cert-manager.io/privatekey-file: consul-key.pem
            csi.cert-manager.io/ca-file: ca.pem

  volumeClaimTemplates:

  - metadata:
      name: consul-data
    spec:
      accessModes: [ ReadWriteOnce ]
      storageClassName: longhorn-retain
      resources:
        requests:
          storage: 100Mi
